/* =========================================================================
   Karthikeyan K U — Central portfolio data
   ========================================================================= */

export const social = {
  github: "https://github.com/Karthikeyan-k-u",
  githubHandle: "Karthikeyan-k-u",
  linkedin: "https://www.linkedin.com/in/karthikeyan-k-u-689858386/",
  linkedinHandle: "karthikeyan-k-u",
  email: "KARTHUKEYAN.KU.cse29@princedrkvasudevan.com",
  certifications:
    "https://www.linkedin.com/in/karthikeyan-k-u-689858386/details/certifications/",
};

export const resume = "Karthikeyan-K-U-Resume.pdf";

/* Homepage statistic strip (truthful data only) */
export const stats = [
  { value: "1", suffix: "", label: "Industry Internship", icon: "briefcase" },
  { value: "5", suffix: "+", label: "Featured Projects", icon: "layers" },
  { value: "40", suffix: "+", label: "GitHub Repositories", icon: "github", dynamic: true },
  { value: "NPTEL", suffix: "", label: "Elite + Silver", icon: "medal" },
  { value: "Full Stack", suffix: "", label: "Learning & Building", icon: "rocket" },
];

/* Experience / Internship entries */
export const experience = [
  {
    role: "Web Development Intern",
    org: "ATC Travelzone",
    date: "June 2026 – Present",
    current: true,
    link: "https://atctravelzone.in/",
    summary:
      "Single-handedly building and maintaining a full-stack travel booking platform from the ground up — covering the customer-facing website, dynamic content pages, and a complete admin CMS. Balancing this real-world development role alongside a dual-degree program (B.E. CSE + IIT Madras).",
    highlights: [
    { label: "Web Engineer", value: "Now", icon: "code" },
    { label: "Full-Stack CMS", value: "Admin", icon: "terminal" },
    { label: "Real-Time Sync", value: "Live", icon: "database" },
    { label: "Admin Panel", value: "In Progress", icon: "terminal" },
    { label: "Deployed on", value: "Linux", icon: "rocket" },
  ],
    tech: [
      "React",
      "TanStack Start",
      "TypeScript",
      "Tailwind CSS",
      "Supabase",
      "Cloudflare Pages",
      "Git",
    ],
    bullets: [
      "Built the entire customer-facing website end-to-end — homepage, packages, destinations, activities, offers, reviews, and booking flow — using React, TanStack Start, TypeScript, and Tailwind CSS.",
      "Designed and developed a full admin CMS panel from scratch: CRUD modules for Bookings, Packages, Destinations, Website Content, Payments, and Settings — including media upload, image preview, and delete-confirmation safeguards.",
      "Integrated Supabase as the backend, connecting live data across public pages and admin panel with real-time sync.",
      "Identified and resolved numerous bugs and edge cases across the site — from broken layouts to data sync issues — bringing the platform to a stable, professional, production-ready state.",
      "Deployed and maintained the live site on Cloudflare Pages, ensuring performance and uptime.",
    ],
  },
];

/* Skill groups — badges only, no fake percentage bars */
export const skills = [
  {
    cat: "Front-End Development",
    icon: "code",
    items: ["HTML5", "CSS3", "JavaScript", "React", "Responsive Design", "DOM Manipulation"],
  },
  {
    cat: "Programming",
    icon: "terminal",
    items: ["Java", "Python"],
  },
  {
    cat: "Database & Backend",
    icon: "database",
    items: ["Supabase", "SQL", "MySQL", "Cloudflare Workers", "Cloudflare D1"],
  },
  {
    cat: "Tools & Platforms",
    icon: "wrench",
    items: ["Git", "GitHub", "VS Code", "Cloudflare Pages", "Figma", "OpenCode"],
  },
  {
    cat: "Core Knowledge",
    icon: "brain",
    items: [
      "Object-Oriented Programming",
      "Data Structures",
      "DBMS",
      "UI/UX Principles",
      "Debugging",
      "Problem Solving",
    ],
  },
];

/* Achievements — verified only */
export const achievements = [
  {
    title: "NPTEL Elite & Silver",
    desc: "Fundamentals of Object-Oriented Programming — Elite & Silver, 78%",
    icon: "trophy",
  },
  {
    title: "Smart India Hackathon",
    desc: "Top 50 at College Level",
    icon: "lightbulb",
  },
  {
    title: "Third Rank in Class XII",
    desc: "Higher Secondary Examination",
    icon: "graduation",
  },
  {
    title: "Subject Topper in Mathematics",
    desc: "Classes XI and XII",
    icon: "calculator",
  },
  {
    title: "Subject Topper in Physics",
    desc: "Class XII",
    icon: "atom",
  },
  {
    title: "Subject Topper in Chemistry",
    desc: "Class XII",
    icon: "flask",
  },
  {
    title: "Subject Topper in Tamil",
    desc: "Class XI",
    icon: "book",
  },
];

/* Education — one consistent CGPA value (8.21) everywhere */
export const education = [
  {
    degree: "B.E. Computer Science & Engineering",
    institution: "Prince Dr. K. Vasudevan College of Engineering",
    years: "2025 – 2029",
    location: "Chennai, India",
    meta: "CGPA: 8.21",
    tag: "Currently Pursuing",
  },
  {
    degree: "BS in Data Science and Applications",
    institution: "Indian Institute of Technology Madras",
    years: "",
    location: "Chennai, India",
    meta: "",
    tag: "Currently Pursuing",
  },
  {
    degree: "Class XII (Higher Secondary)",
    institution: "Dr. Gurusamy Mudaliar T.T.V Higher Secondary School",
    years: "2024 – 2025",
    location: "Tamil Nadu",
    meta: "Percentage: 84%",
    tag: "",
  },
  {
    degree: "Class X (Secondary)",
    institution: "Dr. Gurusamy Mudaliar T.T.V Higher Secondary School",
    years: "2022 – 2023",
    location: "Tamil Nadu",
    meta: "Percentage: 80%",
    tag: "",
  },
];

/* Certifications.
   `url` is the direct credential link when available. Leave "" to fall
   back to the LinkedIn Certifications tab. */
export const certifications = [
  { title: "Fundamentals of Object-Oriented Programming — Elite & Silver, 78%", issuer: "NPTEL", featured: true, url: "https://nptel.ac.in/noc/E_Certificate/NOC26CS87S155030671804591088" },
  { title: "Responsive Web Design (V8)", issuer: "freeCodeCamp", featured: true, url: "https://www.freecodecamp.org/certification/fcc-5829337e-e9e5-46fa-b75f-c7a02e0b4be3/responsive-web-design" },
  { title: "Responsive Web Design (V9)", issuer: "freeCodeCamp", featured: false, url: "https://www.freecodecamp.org/certification/fcc-5829337e-e9e5-46fa-b75f-c7a02e0b4be3/responsive-web-design-v9" },
  { title: "Azure Storage Security Applied Skills", issuer: "Microsoft", featured: true, url: "" },
  { title: "Digital Skills: User Experience", issuer: "Accenture", featured: true, url: "" },
  { title: "Fundamentals of Java", issuer: "Infosys", featured: true, url: "" },
  { title: "Python Fundamentals", issuer: "Infosys", featured: true, url: "" },
  { title: "Claude API", issuer: "Anthropic", featured: true, url: "https://verify.skilljar.com/c/yyvnjqqyo4a7" },
  { title: "MCP Fundamentals", issuer: "Anthropic", featured: true, url: "https://verify.skilljar.com/c/d7vqbdxqv6ra" },
  { title: "AI Fluency: Capabilities & Limitations", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/n9kd3n73coc4" },
  { title: "AI Fluency for Educators", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/4es6anxd4w3j" },
  { title: "AI Fluency for Nonprofits", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/kmjq342y66qk" },
  { title: "AI Fluency for Students", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/nv3jikkz7ojx" },
  { title: "Framework & Foundations", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/s2zgu3iftxiq" },
  { title: "Claude 101", issuer: "Anthropic", featured: false, url: "" },
  { title: "Claude Code 101", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/b726y2vbfyhy" },
  { title: "Code in Action", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/dobvtizzbs2e" },
  { title: "Amazon Bedrock Integration", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/2buyt9ijdbst" },
  { title: "Google Vertex AI Integration", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/ygxewddu2s7k" },
  { title: "Agent Skills", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/g2a4x8m9fj4c" },
  { title: "Subagents", issuer: "Anthropic", featured: false, url: "" },
  { title: "Teaching AI Fluency", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/7dq5gy8fvaez" },
  { title: "Model Context Protocol: Advanced Topics", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/9be6c9w5hjcz" },
  { title: "Java Fundamentals", issuer: "Scaler Topics", featured: false, url: "" },
  { title: "JavaScript Fundamentals", issuer: "Scaler Topics", featured: false, url: "" },
  { title: "Automation with Arduino — Excellent Performance", issuer: "LPB02", featured: false, url: "" },
  { title: "AI Tools & Workshop", issuer: "B10X", featured: false, url: "https://certx.in/certificate/0270772f-3809-4400-b29b-1e1c61cd09971046826" },
];

/* All projects. `featured` controls which appear on the homepage.
   `live` / `repo` are hidden automatically when empty. */
export const projects = [
  {
    id: "atc",
    title: "ATC Travelzone Website",
    cat: "frontend",
    badge: "Web Development Internship Project",
    desc: "Full-stack travel booking platform built during my internship — customer-facing pages, dynamic content, and a complete admin CMS on Supabase + Cloudflare.",
    tech: ["HTML", "CSS", "JavaScript", "React", "Supabase", "Cloudflare", "GitHub"],
    live: "https://atctravelzone.in/",
    repo: "",
    featured: true,
  },
  {
    id: "waste",
    title: "Waste Collection Worker Attendance & Route Register",
    cat: "frontend",
    badge: "Smart India Hackathon 2026",
    desc: "Offline-ready dashboard that records worker attendance, tracks daily route coverage, and connects complaints to routes with synchronization.",
    tech: ["HTML", "CSS", "JavaScript", "Cloudflare Workers", "D1", "IndexedDB"],
    live: "https://waste-worker-attendance-route-register.karthikeyan-k-u-777.workers.dev",
    repo: "https://github.com/Karthikeyan-k-u/Waste-Collection-Worker-Attendance-Route-Register",
    featured: true,
  },
  {
    id: "blood-bank",
    title: "Mass Blood Bank Website",
    cat: "frontend",
    badge: "Personal Project",
    desc: "Responsive frontend connecting donors, recipients, and blood banks — hospital search, donation and request flows, with persistent localStorage data.",
    tech: ["HTML", "CSS", "JavaScript", "localStorage"],
    live: "https://mass-blood-bank.pages.dev/",
    repo: "https://github.com/Karthikeyan-k-u/First-FrontEnd-Project-Mass-Blood-Bank-",
    featured: true,
  },
  {
    id: "bus-tracking",
    title: "College Bus Tracking Interface",
    cat: "frontend",
    badge: "Capstone Project",
    desc: "Real-time bus tracker with live shuttle locations, route and driver details, ETAs, and pickup schedules for safer student commutes.",
    tech: ["HTML", "CSS", "JavaScript", "React"],
    live: "https://college-bus-tracking.pages.dev/html/",
    repo: "https://github.com/Karthikeyan-k-u/Front-End-Web-Capstone-Project",
    featured: true,
  },
  {
    id: "wie",
    title: "Project Showcase (WIE)",
    cat: "frontend",
    badge: "Web Intelligence Engineering",
    desc: "Dark-themed React showcase with gradient orbs, a filterable project grid, and live thumbnails — built for the WIE course.",
    tech: ["React", "Vite", "HTML", "CSS", "JavaScript"],
    live: "https://karthikeyan-k-u.github.io/Project-Showcase--WIE-/",
    repo: "https://github.com/Karthikeyan-k-u/Project-Showcase--WIE-",
    featured: true,
  },
  {
    id: "portfolio",
    title: "Personal Portfolio Website",
    cat: "frontend",
    badge: "Personal Project",
    desc: "A modern, responsive React portfolio with project, skills, education, and certification sections — deployed on Cloudflare Pages.",
    tech: ["React", "HTML", "CSS", "JavaScript", "Cloudflare Pages"],
    live: "https://portfolio-karthikeyan-k-u.pages.dev",
    repo: "https://github.com/Karthikeyan-k-u/Personal-Portfolio---Karthikeyan-K-U-",
    featured: true,
  },
  {
    id: "quizhub",
    title: "QuizHub Examination Portal",
    cat: "frontend",
    badge: "Personal Project",
    desc: "Reactive EdTech examination portal with Student and Staff dashboards, quiz management, timed assessments, and instant results.",
    tech: ["React", "TypeScript", "Vite", "Tailwind CSS", "React Router", "shadcn/ui", "Lucide React"],
    live: "https://karthikeyan-k-u.github.io/Quizhub-examination-portal-Using-react-/",
    repo: "https://github.com/Karthikeyan-k-u/Quizhub-examination-portal-Using-react-",
    featured: true,
  },
  {
    id: "unitly",
    title: "Unitly — Unit Conversion App",
    cat: "frontend",
    badge: "Personal Project",
    desc: "Modern, responsive unit converter with real-time conversions across 11 categories, swap/copy, history, favorites, presets, and dark mode.",
    tech: ["React", "JavaScript", "HTML", "CSS"],
    live: "https://karthikeyan-k-u.github.io/Unitly-Unit-Conversion-Using-React-/",
    repo: "https://github.com/Karthikeyan-k-u/Unitly-Unit-Conversion-Using-React-",
    featured: true,
  },
  {
    id: "weather-map",
    title: "Weather Forecast with Real-Time Maps",
    cat: "frontend",
    badge: "Personal Project",
    desc: "Weather app with current conditions, hourly and 7-day forecasts, and interactive Leaflet maps with location search for places across India.",
    tech: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Leaflet"],
    live: "https://karthikeyan-k-u.github.io/Weather-forecast-with-real-time-maps/",
    repo: "https://github.com/Karthikeyan-k-u/Weather-forecast-with-real-time-maps",
    featured: true,
  },
  {
    id: "contact-mgmt",
    title: "Contact Management with Multiple Apps",
    cat: "frontend",
    badge: "Personal Project",
    desc: "Unified contact platform bringing contacts, groups, interactions, and follow-ups together — WhatsApp, Instagram, SMS, email, and calls in one dashboard.",
    tech: ["React", "TypeScript", "React Query", "CSS"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Contact-Management-with-Multiple-Apps",
    featured: true,
  },
  {
    id: "uiux",
    title: "Personal UI/UX Design Projects",
    cat: "uiux",
    badge: "UI/UX Design",
    desc: "Responsive UI layouts and application prototypes designed for self-learning — exploring UX principles, visual hierarchy, and interface design.",
    tech: ["Figma", "UX Principles", "Visual Hierarchy", "Responsive Design"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u",
    featured: false,
  },
  {
    id: "html-basics",
    title: "HTML Basics Through Projects",
    cat: "frontend",
    badge: "Learning",
    desc: "Hands-on HTML projects covering semantic tags, forms, tables, and document structure — a practical foundation for web development.",
    tech: ["HTML", "Semantic Tags", "Forms"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Learning-HTML-Basics-Through-a-Project",
    featured: false,
  },
  {
    id: "css-practice",
    title: "CSS Practice Projects",
    cat: "frontend",
    badge: "Learning",
    desc: "Practice-focused CSS work covering Flexbox, Grid, animations, transitions, pseudo-classes, and responsive design techniques.",
    tech: ["CSS", "Flexbox", "Grid", "Animations"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Learning-CSS-Through-Practice",
    featured: false,
  },
  {
    id: "js-projects",
    title: "JavaScript Projects",
    cat: "frontend",
    badge: "Learning",
    desc: "Interactive JavaScript mini-projects demonstrating DOM manipulation, event handling, localStorage, and dynamic UI updates.",
    tech: ["JavaScript", "DOM", "Events"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Learning-Java-Script-through-project",
    featured: false,
  },
  {
    id: "stopwatch",
    title: "Stop-Watch App",
    cat: "frontend",
    badge: "Web Technology — Unit 1",
    desc: "Accurate, millisecond-precision stopwatch with start/stop, reset, scrollable lap history, glassmorphism styling, and smooth animations.",
    tech: ["HTML", "CSS", "JavaScript"],
    live: "https://karthikeyan-k-u.github.io/Stop-Watch-WebTechnology-Unit-1-/",
    repo: "https://github.com/Karthikeyan-k-u/Stop-Watch-WebTechnology-Unit-1-",
    featured: false,
  },
  {
    id: "task-manager",
    title: "Task Management App",
    cat: "frontend",
    badge: "Web Technology — Unit 1",
    desc: "Add tasks with deadlines, watch live countdowns, mark complete, undo or delete, and get overdue alerts — all persisted in localStorage.",
    tech: ["HTML", "CSS", "JavaScript"],
    live: "https://karthikeyan-k-u.github.io/Task-Management-WebTechnology-Unit-1-/",
    repo: "https://github.com/Karthikeyan-k-u/Task-Management-WebTechnology-Unit-1-",
    featured: false,
  },
  {
    id: "chill-out",
    title: "Chill & Out Online Food Ordering",
    cat: "frontend",
    badge: "Personal Project",
    desc: "Responsive food-ordering frontend with a modern menu grid, quantity controls, a customer detail form, and live order-summary totals.",
    tech: ["HTML", "CSS", "JavaScript"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Chill-Out-Online-Food-Ordering-System-",
    featured: false,
  },
  {
    id: "mk-institute",
    title: "MK Institute of Technology Website",
    cat: "frontend",
    badge: "Practice Project",
    desc: "Responsive educational institution landing page with navigation, video hero, statistics counters, course filtering, and a campus gallery.",
    tech: ["HTML", "CSS"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/MK-Institute-of-Technology-Website-",
    featured: false,
  },
  {
    id: "student-teacher",
    title: "Student–Teacher Management System",
    cat: "java-oop",
    badge: "Java OOP",
    desc: "Java console app using interfaces, abstract classes, inheritance, and polymorphism to manage student and teacher records through a menu.",
    tech: ["Java", "OOP", "Console"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Student-Teacher-Management-System-Using-Java",
    featured: false,
  },
  {
    id: "student-mgmt",
    title: "Student Management System",
    cat: "java-oop",
    badge: "Java OOP",
    desc: "Java OOP console app that reads comma-separated student data, generates IDs, and displays records — constructors, arrays, and I/O in action.",
    tech: ["Java", "OOP", "CRUD"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Student_Management_System_Using_Java",
    featured: false,
  },
  {
    id: "doctor-patient",
    title: "Doctor–Patient Management System",
    cat: "java-oop",
    badge: "Java OOP",
    desc: "Java console app applying abstraction, inheritance, interfaces, and polymorphism to manage doctor and patient records.",
    tech: ["Java", "OOP", "Inheritance"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/-Doctor-Patient-Management-System-Using-Java",
    featured: false,
  },
  {
    id: "library-console",
    title: "Library Management System (Console)",
    cat: "java-oop",
    badge: "Java OOP",
    desc: "Java console app managing book records with arrays, classes, and structured display — a clean introduction to collections and user input.",
    tech: ["Java", "OOP", "Collections"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Library_Management_System_Using_Java",
    featured: false,
  },
  {
    id: "library-oop",
    title: "Library Management System (OOP Console)",
    cat: "java-oop",
    badge: "Java OOP",
    desc: "Menu-driven Java library manager for adding, removing, searching, issuing, and returning books — OOP, collections, and input validation.",
    tech: ["Java", "OOP", "Console"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Library-Management-System-using-Oops-Java-Console-Based-",
    featured: false,
  },
  {
    id: "employee-role",
    title: "Employee Role Display System",
    cat: "java-oop",
    badge: "Java OOP",
    desc: "Shows inheritance and polymorphism in action by dynamically creating Employee, Manager, or Developer objects and displaying their roles.",
    tech: ["Java", "OOP", "Polymorphism"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Employee-Role-Display-System-Using-Java",
    featured: false,
  },
  {
    id: "vehicle-eval",
    title: "Vehicle Evaluation System",
    cat: "java-oop",
    badge: "Java OOP",
    desc: "Evaluates Bike and Car types with interfaces, inheritance, method overriding, and polymorphism — custom evaluation for each vehicle.",
    tech: ["Java", "OOP", "Abstract Classes"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Vehicle-Evaluation-System-Using-Java",
    featured: false,
  },
  {
    id: "bike-sales",
    title: "Bike Sales Report System",
    cat: "java-oop",
    badge: "Java OOP",
    desc: "Java console app that records customer bike purchases and prints structured sales reports — OOP, input handling, and formatted output.",
    tech: ["Java", "OOP", "Reporting"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Bike_Sales_Report_System_Using_Java",
    featured: false,
  },
  {
    id: "food-ordering",
    title: "Food Ordering System (OOP + Inheritance)",
    cat: "java-oop",
    badge: "Java OOP",
    desc: "Menu-driven Java food ordering with veg, non-veg, and dessert items using inheritance and abstraction — dynamic total-bill calculation.",
    tech: ["Java", "OOP", "Inheritance"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Food-Ordering-System-using-Java-OOP-and-Inheritance-",
    featured: false,
  },
  {
    id: "bank-account",
    title: "Bank Account Management System",
    cat: "java-oop",
    badge: "Java OOP",
    desc: "Java console bank system using abstraction, inheritance, and method overriding for deposits, withdrawals, and account details.",
    tech: ["Java", "OOP", "Encapsulation"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Bank_Account_Management_System_Using_Java",
    featured: false,
  },
  {
    id: "payroll",
    title: "Payroll System",
    cat: "java-oop",
    badge: "Java OOP",
    desc: "Computes gross and net salary from basic pay with classes, encapsulation, and formatted output — allowances and tax deductions included.",
    tech: ["Java", "OOP", "Method Overriding"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Payroll_Management_System_Using_Java",
    featured: false,
  },
  {
    id: "inventory",
    title: "Inventory System",
    cat: "java-oop",
    badge: "Java OOP",
    desc: "HashMap-backed inventory manager with add, restock, sell, check stock, display, and remove operations plus input validation.",
    tech: ["Java", "OOP", "Collections"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Inventory-Management-System-Using-Java",
    featured: false,
  },
  {
    id: "employee-mgmt",
    title: "Employee Management System",
    cat: "java-oop",
    badge: "Java OOP",
    desc: "Java console app capturing employee details with encapsulation, constructors, and method overriding — clean, formatted output.",
    tech: ["Java", "OOP", "CRUD"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Employee_Management_System_Using_Java",
    featured: false,
  },
  {
    id: "movie-console",
    title: "Movie Ticket Booking System (Console)",
    cat: "java-oop",
    badge: "Java OOP",
    desc: "Java console movie booking system — manage shows, check seat availability, book tickets first-come first-served, and view bookings.",
    tech: ["Java", "OOP", "Console"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Movie-Ticket-Booking-System-Using-Java",
    featured: false,
  },
  {
    id: "generic-library",
    title: "Generic Library System",
    cat: "java-oop",
    badge: "Java Generics",
    desc: "Type-safe library built with Java generics, custom exceptions, and collections — add, display, and search books by ID.",
    tech: ["Java", "Generics", "OOP"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Generic-Library-Management-System-Using-Java",
    featured: false,
  },
  {
    id: "quiz-swing",
    title: "Timed Quiz Application",
    cat: "swing",
    badge: "Java Swing",
    desc: "Swing quiz GUI with a 5-second countdown per question, auto-advance, score tracking, and a clean results screen.",
    tech: ["Java", "Swing", "Timer"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Timed-Quiz-Application-using-Java-Swing",
    featured: false,
  },
  {
    id: "vehicle-rental",
    title: "Vehicle Rental System (Factory Pattern)",
    cat: "swing",
    badge: "Java Swing",
    desc: "Swing app using the Factory pattern for Car, Bike, and Truck rental — dynamic cost calculation with simulated processing and validation.",
    tech: ["Java", "Swing", "Factory Pattern"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Vehicle-Rental-System-using-Java-Swing-and-Factory-Design-Pattern",
    featured: false,
  },
  {
    id: "food-delivery",
    title: "Food Delivery System (Strategy Pattern)",
    cat: "swing",
    badge: "Java Swing",
    desc: "Swing food-delivery app offering Cash, Card, or UPI via the Strategy pattern — dynamic order processing with multithreading.",
    tech: ["Java", "Swing", "Strategy Pattern"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Food-Delivery-Application-using-Java-Swing-and-Strategy-Design-Pattern",
    featured: false,
  },
  {
    id: "bank-swing",
    title: "Bank Management System (Swing + OOP)",
    cat: "swing",
    badge: "Java Swing",
    desc: "GUI banking app with Savings and Current accounts, deposits, withdrawals, custom exceptions, and overdraft support.",
    tech: ["Java", "Swing", "OOP"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Bank-Management-System-using-Java-Swing-and-OOP-Concepts",
    featured: false,
  },
  {
    id: "movie-gui",
    title: "Movie Ticket Booking System (GUI)",
    cat: "swing",
    badge: "Java Swing",
    desc: "Swing GUI for movie ticket booking with a visual seat map, showtime selection, and printable billing — a polished desktop version.",
    tech: ["Java", "Swing", "GUI"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Movie-Ticket-Booking-System-Using-Java",
    featured: false,
  },
  {
    id: "dice-game",
    title: "Dice Game (Player vs Computer)",
    cat: "python",
    badge: "Python",
    desc: "Python CLI dice game — roll against the computer, determine the winner, and save score history to a file through a menu.",
    tech: ["Python", "Random", "Game Logic"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Dice-Game-Player-vs-Computer-using-Python",
    featured: false,
  },
  {
    id: "password-checker",
    title: "Password Checker",
    cat: "python",
    badge: "Python",
    desc: "Enforces strong passwords — 8+ characters with a number, uppercase letter, and special character — retrying until the input is valid.",
    tech: ["Python", "Regex", "Security"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Valid-Password-Checker-Using-Python",
    featured: false,
  },
  {
    id: "student-csv",
    title: "Student Record System (CSV-based)",
    cat: "python",
    badge: "Python",
    desc: "CSV-backed student record manager with add, view, update, and delete — persistent storage through Python file handling.",
    tech: ["Python", "CSV", "File I/O"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Student-Record-Management-System-using-CSV-in-Python",
    featured: false,
  },
  {
    id: "student-python-csv",
    title: "Student Management System (CSV-based)",
    cat: "python",
    badge: "Python",
    desc: "Menu-driven Python student manager with full CRUD, persisted to CSV between sessions using the built-in csv module.",
    tech: ["Python", "CSV", "File I/O"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Student-Management-System-Using-Python-CSV-based-",
    featured: false,
  },
  {
    id: "notes-saver",
    title: "Notes Saver System",
    cat: "python",
    badge: "Python",
    desc: "Python CLI notes app that saves each note as a .txt file, prevents duplicate titles, and handles missing notes gracefully.",
    tech: ["Python", "File I/O", "CLI"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Notes-Saver-System-Using-Python-",
    featured: false,
  },
  {
    id: "library-python",
    title: "Library System (Python)",
    cat: "python",
    badge: "Python",
    desc: "Simple Python library manager — add, view, borrow, return, and search books through an easy command-line menu.",
    tech: ["Python", "OOP", "Lists"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Library-Management-System-Using-Python",
    featured: false,
  },
  {
    id: "rps-game",
    title: "Rock Paper Scissors Game",
    cat: "python",
    badge: "Python",
    desc: "Play Rock Paper Scissors against the computer with random selection, input validation, round results, and replay options.",
    tech: ["Python", "Random", "Game Logic"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Rock-Paper-Scissors-Game-Using-Python",
    featured: false,
  },
  {
    id: "mcq-quiz",
    title: "MCQ Quiz App",
    cat: "python",
    badge: "Python",
    desc: "Console-based 20-question MCQ quiz with score tracking and correction review for wrong answers — replay or exit at the end.",
    tech: ["Python", "JSON", "Logic"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/MCQ_quiz_app_using_python",
    featured: false,
  },
  {
    id: "number-guessing",
    title: "Number Guessing Game",
    cat: "python",
    badge: "Python",
    desc: "Interactive guess-the-number game — the computer picks 1–100 and you have 10 attempts with 'too high / too low' hints.",
    tech: ["Python", "Random", "Game Logic"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/Number-Guessing-Game-Using-Python-",
    featured: false,
  },
  {
    id: "atm-system",
    title: "ATM System",
    cat: "python",
    badge: "Python",
    desc: "Python ATM simulation with balance check, deposit, and withdrawal — the balance updates live until you exit.",
    tech: ["Python", "OOP", "Authentication"],
    live: "",
    repo: "https://github.com/Karthikeyan-k-u/ATM_System_using_Python-",
    featured: false,
  },
];