/* =========================================================================
   Karthikeyan K U — Central portfolio data
   Shared by index.html and projects.html
   ========================================================================= */
window.PORTFOLIO = {
  social: {
    github: "https://github.com/Karthikeyan-k-u",
    githubHandle: "Karthikeyan-k-u",
    linkedin: "https://www.linkedin.com/in/karthikeyan-k-u-689858386/",
    linkedinHandle: "karthikeyan-k-u",
    email: "KARTHUKEYAN.KU.cse29@princedrkvasudevan.com",
    certifications:
      "https://www.linkedin.com/in/karthikeyan-k-u-689858386/details/certifications/",
  },

  resume: "Karthikeyan-K-U-Resume.pdf",

  /* Homepage statistic strip (truthful data only) */
  stats: [
    { value: "1", suffix: "", label: "Industry Internship", icon: "briefcase" },
    { value: "5", suffix: "+", label: "Featured Projects", icon: "layers" },
    { value: "40", suffix: "+", label: "GitHub Repositories", icon: "github", dynamic: true },
    { value: "NPTEL", suffix: "", label: "Elite + Silver", icon: "medal" },
    { value: "Full Stack", suffix: "", label: "Learning & Building", icon: "rocket" },
  ],

  /* Skill groups — badges only, no fake percentage bars */
  skills: [
    {
      cat: "Front-End Development",
      icon: "code",
      items: ["HTML5", "CSS3", "JavaScript", "React", "Responsive Design", "DOM Manipulation"],
    },
    {
      cat: "Programming",
      icon: "terminal",
      items: ["Java", "Python"],
    },
    {
      cat: "Database & Backend",
      icon: "database",
      items: ["Supabase", "SQL", "MySQL", "Cloudflare Workers", "Cloudflare D1"],
    },
    {
      cat: "Tools & Platforms",
      icon: "wrench",
      items: ["Git", "GitHub", "VS Code", "Cloudflare Pages", "Figma", "OpenCode"],
    },
    {
      cat: "Core Knowledge",
      icon: "brain",
      items: [
        "Object-Oriented Programming",
        "Data Structures",
        "DBMS",
        "UI/UX Principles",
        "Debugging",
        "Problem Solving",
      ],
    },
  ],

  /* Achievements — verified only */
  achievements: [
    {
      title: "NPTEL Elite & Silver",
      desc: "Fundamentals of Object-Oriented Programming — Elite & Silver, 78%",
      icon: "trophy",
    },
    {
      title: "Smart India Hackathon",
      desc: "Top 50 at College Level",
      icon: "lightbulb",
    },
    {
      title: "Third Rank in Class XII",
      desc: "Higher Secondary Examination",
      icon: "graduation",
    },
    {
      title: "Subject Topper in Mathematics",
      desc: "Classes XI and XII",
      icon: "calculator",
    },
    {
      title: "Subject Topper in Physics",
      desc: "Class XII",
      icon: "atom",
    },
    {
      title: "Subject Topper in Chemistry",
      desc: "Class XII",
      icon: "flask",
    },
    {
      title: "Subject Topper in Tamil",
      desc: "Class XI",
      icon: "book",
    },
  ],

  /* Education — one consistent CGPA value (8.21) everywhere */
  education: [
    {
      degree: "B.E. Computer Science & Engineering",
      institution: "Prince Dr. K. Vasudevan College of Engineering",
      years: "2025 – 2029",
      location: "Chennai, India",
      meta: "CGPA: 8.21",
      tag: "Currently Pursuing",
    },
    {
      degree: "BS in Data Science and Applications",
      institution: "Indian Institute of Technology Madras",
      years: "Currently Pursuing",
      location: "Chennai, India",
      meta: "",
      tag: "",
    },
    {
      degree: "Class XII (Higher Secondary)",
      institution: "Dr. Gurusamy Mudaliar T.T.V Higher Secondary School",
      years: "2024 – 2025",
      location: "Tamil Nadu",
      meta: "Percentage: 84%",
      tag: "",
    },
    {
      degree: "Class X (Secondary)",
      institution: "Dr. Gurusamy Mudaliar T.T.V Higher Secondary School",
      years: "2022 – 2023",
      location: "Tamil Nadu",
      meta: "Percentage: 80%",
      tag: "",
    },
  ],

  /* Certifications.
     `url` is the direct credential link when available. Leave "" to fall
     back to the LinkedIn Certifications tab. Fill in your direct URLs here. */
  certifications: [
    { title: "Fundamentals of Object-Oriented Programming — Elite & Silver, 78%", issuer: "NPTEL", featured: true, url: "https://nptel.ac.in/noc/E_Certificate/NOC26CS87S155030671804591088" },
    { title: "Responsive Web Design (V8)", issuer: "freeCodeCamp", featured: true, url: "https://www.freecodecamp.org/certification/fcc-5829337e-e9e5-46fa-b75f-c7a02e0b4be3/responsive-web-design" },
    { title: "Responsive Web Design (V9)", issuer: "freeCodeCamp", featured: false, url: "https://www.freecodecamp.org/certification/fcc-5829337e-e9e5-46fa-b75f-c7a02e0b4be3/responsive-web-design-v9" },
    { title: "Azure Storage Security Applied Skills", issuer: "Microsoft", featured: true, url: "" },
    { title: "Digital Skills: User Experience", issuer: "Accenture", featured: true, url: "" },
    { title: "Fundamentals of Java", issuer: "Infosys", featured: true, url: "" },
    { title: "Python Fundamentals", issuer: "Infosys", featured: true, url: "" },
    { title: "Claude API", issuer: "Anthropic", featured: true, url: "https://verify.skilljar.com/c/yyvnjqqyo4a7" },
    { title: "MCP Fundamentals", issuer: "Anthropic", featured: true, url: "https://verify.skilljar.com/c/d7vqbdxqv6ra" },
    { title: "AI Fluency: Capabilities & Limitations", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/n9kd3n73coc4" },
    { title: "AI Fluency for Educators", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/4es6anxd4w3j" },
    { title: "AI Fluency for Nonprofits", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/kmjq342y66qk" },
    { title: "AI Fluency for Students", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/nv3jikkz7ojx" },
    { title: "Framework & Foundations", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/s2zgu3iftxiq" },
    { title: "Claude 101", issuer: "Anthropic", featured: false, url: "" },
    { title: "Claude Code 101", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/b726y2vbfyhy" },
    { title: "Code in Action", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/dobvtizzbs2e" },
    { title: "Amazon Bedrock Integration", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/2buyt9ijdbst" },
    { title: "Google Vertex AI Integration", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/ygxewddu2s7k" },
    { title: "Agent Skills", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/g2a4x8m9fj4c" },
    { title: "Subagents", issuer: "Anthropic", featured: false, url: "" },
    { title: "Teaching AI Fluency", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/7dq5gy8fvaez" },
    { title: "Model Context Protocol: Advanced Topics", issuer: "Anthropic", featured: false, url: "https://verify.skilljar.com/c/9be6c9w5hjcz" },
    { title: "Java Fundamentals", issuer: "Scaler Topics", featured: false, url: "" },
    { title: "JavaScript Fundamentals", issuer: "Scaler Topics", featured: false, url: "" },
    { title: "Automation with Arduino — Excellent Performance", issuer: "LPB02", featured: false, url: "" },
    { title: "AI Tools & Workshop", issuer: "B10X", featured: false, url: "https://certx.in/certificate/0270772f-3809-4400-b29b-1e1c61cd09971046826" },
  ],

  /* All projects. `featured` controls which appear on the homepage.
     `live` / `repo` are hidden automatically when empty.
     ATC Travelzone has no public repo, so `repo` stays empty. */
  projects: [
    {
      id: "atc",
      title: "ATC Travelzone Website",
      cat: "frontend",
      badge: "Web Development Internship Project",
      desc: "Responsive travel-platform pages built during my internship — destinations, packages, activities, offers, reviews, and booking flows on Supabase + Cloudflare.",
      tech: ["HTML", "CSS", "JavaScript", "React", "Supabase", "Cloudflare", "GitHub"],
      live: "https://atctravelzone.in/",
      repo: "",
      featured: true,
    },
    {
      id: "waste",
      title: "Waste Collection Worker Attendance & Route Register",
      cat: "frontend",
      badge: "Smart India Hackathon 2026",
      desc: "Dashboard with attendance records, route tracking, complaint management, and detailed record views for the waste collection workflow. Offline support with a Cloudflare Workers + D1 backend.",
      tech: ["HTML", "CSS", "JavaScript", "Cloudflare Workers", "D1", "IndexedDB"],
      live: "https://waste-worker-attendance-route-register.karthikeyan-k-u-777.workers.dev",
      repo: "https://github.com/Karthikeyan-k-u/Waste-Collection-Worker-Attendance-Route-Register",
      featured: true,
    },
    {
      id: "blood-bank",
      title: "Mass Blood Bank Website",
      cat: "frontend",
      badge: "Personal Project",
      desc: "Responsive multi-page website with hospital search and filtering, form validation, dropdown interactions, and persistent browser data using localStorage.",
      tech: ["HTML", "CSS", "JavaScript", "localStorage"],
      live: "https://mass-blood-bank.pages.dev/",
      repo: "https://github.com/Karthikeyan-k-u/First-FrontEnd-Project-Mass-Blood-Bank-",
      featured: true,
    },
    {
      id: "bus-tracking",
      title: "College Bus Tracking Interface",
      cat: "frontend",
      badge: "Capstone Project",
      desc: "Responsive interface displaying bus routes, live status, estimated arrival times, and map-oriented details built with React.",
      tech: ["HTML", "CSS", "JavaScript", "React"],
      live: "https://college-bus-tracking.pages.dev/html/",
      repo: "https://github.com/Karthikeyan-k-u/Front-End-Web-Capstone-Project",
      featured: true,
    },
    {
      id: "wie",
      title: "Project Showcase (WIE)",
      cat: "frontend",
      badge: "Web Intelligence Engineering",
      desc: "React-based project showcase portfolio with a dark theme, gradient orbs, and a filterable project grid with live thumbnails and category-based filtering.",
      tech: ["React", "Vite", "HTML", "CSS", "JavaScript"],
      live: "https://karthikeyan-k-u.github.io/Project-Showcase--WIE-/",
      repo: "https://github.com/Karthikeyan-k-u/Project-Showcase--WIE-",
      featured: true,
    },
    {
      id: "portfolio",
      title: "Personal Portfolio Website",
      cat: "frontend",
      badge: "Personal Project",
      desc: "Designed and deployed this portfolio site with project, skills, certification, and achievement sections, plus direct GitHub and LinkedIn links, on Cloudflare Pages.",
      tech: ["HTML", "CSS", "JavaScript", "Cloudflare Pages"],
      live: "https://portfolio-karthikeyan-k-u.pages.dev",
      repo: "https://github.com/Karthikeyan-k-u/Personal-Portfolio---Karthikeyan-K-U-",
      featured: true,
    },
    {
      id: "uiux",
      title: "Personal UI/UX Design Projects",
      cat: "uiux",
      badge: "UI/UX Design",
      desc: "Designed UI layouts and application prototypes for self-learning practice. Improved understanding of UX principles, visual hierarchy, and responsive interface design techniques.",
      tech: ["Figma", "UX Principles", "Visual Hierarchy", "Responsive Design"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u",
      featured: false,
    },
    {
      id: "html-basics",
      title: "HTML Basics Through Projects",
      cat: "frontend",
      badge: "Learning",
      desc: "A series of small HTML projects built while learning the fundamentals — semantic tags, forms, tables, and document structure from the ground up.",
      tech: ["HTML", "Semantic Tags", "Forms"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Learning-HTML-Basics-Through-a-Project",
      featured: false,
    },
    {
      id: "css-practice",
      title: "CSS Practice Projects",
      cat: "frontend",
      badge: "Learning",
      desc: "Practice-focused CSS projects covering Flexbox, Grid, animations, transitions, pseudo-classes, and responsive design techniques.",
      tech: ["CSS", "Flexbox", "Grid", "Animations"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Learning-CSS-Through-Practice",
      featured: false,
    },
    {
      id: "js-projects",
      title: "JavaScript Projects",
      cat: "frontend",
      badge: "Learning",
      desc: "Collection of JavaScript mini-projects covering DOM manipulation, event handling, local storage, and interactive UI components.",
      tech: ["JavaScript", "DOM", "Events"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Learning-Java-Script-through-project",
      featured: false,
    },
    {
      id: "stopwatch",
      title: "Stop-Watch App",
      cat: "frontend",
      badge: "Web Technology — Unit 1",
      desc: "Interactive stopwatch web application with start, pause, reset, and lap-style controls built as a Web Technology coursework unit.",
      tech: ["HTML", "CSS", "JavaScript"],
      live: "https://karthikeyan-k-u.github.io/Stop-Watch-WebTechnology-Unit-1-/",
      repo: "https://github.com/Karthikeyan-k-u/Stop-Watch-WebTechnology-Unit-1-",
      featured: false,
    },
    {
      id: "task-manager",
      title: "Task Management App",
      cat: "frontend",
      badge: "Web Technology — Unit 1",
      desc: "Task management web application for adding, completing, and removing tasks with a clean, responsive interface. Built as a Web Technology coursework unit.",
      tech: ["HTML", "CSS", "JavaScript"],
      live: "https://karthikeyan-k-u.github.io/Task-Management-WebTechnology-Unit-1-/",
      repo: "https://github.com/Karthikeyan-k-u/Task-Management-WebTechnology-Unit-1-",
      featured: false,
    },
    {
      id: "chill-out",
      title: "Chill & Out Online Food Ordering",
      cat: "frontend",
      badge: "Personal Project",
      desc: "Responsive food-ordering front end with a modern menu grid, quantity selection, a customer detail form, and live order-summary calculations.",
      tech: ["HTML", "CSS", "JavaScript"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Chill-Out-Online-Food-Ordering-System-",
      featured: false,
    },
    {
      id: "mk-institute",
      title: "MK Institute of Technology Website",
      cat: "frontend",
      badge: "Practice Project",
      desc: "Multi-section institutional website layout with navigation, hero, course highlights, and contact information — a practice build.",
      tech: ["HTML", "CSS"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/MK-Institute-of-Technology-Website-",
      featured: false,
    },
    {
      id: "student-teacher",
      title: "Student–Teacher Management System",
      cat: "java-oop",
      badge: "Java OOP",
      desc: "Console-based Java application managing student and teacher records using OOP principles — encapsulation, inheritance, and polymorphism.",
      tech: ["Java", "OOP", "Console"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Student-Teacher-Management-System-Using-Java",
      featured: false,
    },
    {
      id: "student-mgmt",
      title: "Student Management System",
      cat: "java-oop",
      badge: "Java OOP",
      desc: "Java OOP console application for adding, viewing, updating, and removing student records with a clean class-based architecture.",
      tech: ["Java", "OOP", "CRUD"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Student_Management_System_Using_Java",
      featured: false,
    },
    {
      id: "doctor-patient",
      title: "Doctor–Patient Management System",
      cat: "java-oop",
      badge: "Java OOP",
      desc: "Manages doctor and patient interactions using object-oriented design — appointments, records, and role-based access via class hierarchies.",
      tech: ["Java", "OOP", "Inheritance"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/-Doctor-Patient-Management-System-Using-Java",
      featured: false,
    },
    {
      id: "library-console",
      title: "Library Management System (Console)",
      cat: "java-oop",
      badge: "Java OOP",
      desc: "Console-based library system for issuing, returning, and cataloguing books. Implements encapsulation and collection-based storage.",
      tech: ["Java", "OOP", "Collections"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Library_Management_System_Using_Java",
      featured: false,
    },
    {
      id: "library-oop",
      title: "Library Management System (OOP Console)",
      cat: "java-oop",
      badge: "Java OOP",
      desc: "OOP-driven console library system built to reinforce class design, inheritance, and structured data handling.",
      tech: ["Java", "OOP", "Console"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Library-Management-System-using-Oops-Java-Console-Based-",
      featured: false,
    },
    {
      id: "employee-role",
      title: "Employee Role Display System",
      cat: "java-oop",
      badge: "Java OOP",
      desc: "Demonstrates polymorphism and method overriding by displaying different employee roles and their responsibilities dynamically.",
      tech: ["Java", "OOP", "Polymorphism"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Employee-Role-Display-System-Using-Java",
      featured: false,
    },
    {
      id: "vehicle-eval",
      title: "Vehicle Evaluation System",
      cat: "java-oop",
      badge: "Java OOP",
      desc: "Evaluates vehicle attributes using class hierarchies and abstract methods — covers cars, bikes, and trucks with type-specific evaluation logic.",
      tech: ["Java", "OOP", "Abstract Classes"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Vehicle-Evaluation-System-Using-Java",
      featured: false,
    },
    {
      id: "bike-sales",
      title: "Bike Sales Report System",
      cat: "java-oop",
      badge: "Java OOP",
      desc: "Generates formatted sales reports for a bike dealership using OOP — tracks models, quantities, and revenue via encapsulated objects.",
      tech: ["Java", "OOP", "Reporting"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Bike_Sales_Report_System_Using_Java",
      featured: false,
    },
    {
      id: "food-ordering",
      title: "Food Ordering System (OOP + Inheritance)",
      cat: "java-oop",
      badge: "Java OOP",
      desc: "Console-based food ordering system using OOP and inheritance to model menu categories, items, and order processing workflows.",
      tech: ["Java", "OOP", "Inheritance"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Food-Ordering-System-using-Java-OOP-and-Inheritance-",
      featured: false,
    },
    {
      id: "bank-account",
      title: "Bank Account Management System",
      cat: "java-oop",
      badge: "Java OOP",
      desc: "Handles bank accounts (savings, current) with deposit, withdrawal, and balance operations using Java OOP encapsulation and inheritance.",
      tech: ["Java", "OOP", "Encapsulation"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Bank_Account_Management_System_Using_Java",
      featured: false,
    },
    {
      id: "payroll",
      title: "Payroll System",
      cat: "java-oop",
      badge: "Java OOP",
      desc: "Calculates and displays employee payroll including base salary, deductions, and net pay using OOP class structures and method overriding.",
      tech: ["Java", "OOP", "Method Overriding"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Payroll_Management_System_Using_Java",
      featured: false,
    },
    {
      id: "inventory",
      title: "Inventory System",
      cat: "java-oop",
      badge: "Java OOP",
      desc: "Tracks product inventory with stock-in, stock-out, and reorder logic. Uses encapsulated Java classes to manage product data.",
      tech: ["Java", "OOP", "Collections"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Inventory-Management-System-Using-Java",
      featured: false,
    },
    {
      id: "employee-mgmt",
      title: "Employee Management System",
      cat: "java-oop",
      badge: "Java OOP",
      desc: "Full-featured console app for managing employee records — add, update, search, and delete with structured OOP design.",
      tech: ["Java", "OOP", "CRUD"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Employee_Management_System_Using_Java",
      featured: false,
    },
    {
      id: "movie-console",
      title: "Movie Ticket Booking System (Console)",
      cat: "java-oop",
      badge: "Java OOP",
      desc: "Console-based movie ticket booking with seat selection, show scheduling, and billing using Java OOP classes.",
      tech: ["Java", "OOP", "Console"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Movie-Ticket-Booking-System-Using-Java",
      featured: false,
    },
    {
      id: "generic-library",
      title: "Generic Library System",
      cat: "java-oop",
      badge: "Java Generics",
      desc: "Uses Java Generics to build a flexible, type-safe library system that works across multiple data types and collection structures.",
      tech: ["Java", "Generics", "OOP"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Generic-Library-Management-System-Using-Java",
      featured: false,
    },
    {
      id: "quiz-swing",
      title: "Timed Quiz Application",
      cat: "swing",
      badge: "Java Swing",
      desc: "GUI-based quiz app with countdown timer, multiple-choice questions, score tracking, and a results screen built in Java Swing.",
      tech: ["Java", "Swing", "Timer"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Timed-Quiz-Application-using-Java-Swing",
      featured: false,
    },
    {
      id: "vehicle-rental",
      title: "Vehicle Rental System (Factory Pattern)",
      cat: "swing",
      badge: "Java Swing",
      desc: "Java Swing app implementing the Factory design pattern for vehicle rental. Clean architecture with GUI controls for booking and management.",
      tech: ["Java", "Swing", "Factory Pattern"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Vehicle-Rental-System-using-Java-Swing-and-Factory-Design-Pattern",
      featured: false,
    },
    {
      id: "food-delivery",
      title: "Food Delivery System (Strategy Pattern)",
      cat: "swing",
      badge: "Java Swing",
      desc: "Java Swing app using the Strategy design pattern for swappable delivery algorithms. GUI-driven order flow with modular, extensible delivery logic.",
      tech: ["Java", "Swing", "Strategy Pattern"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Food-Delivery-Application-using-Java-Swing-and-Strategy-Design-Pattern",
      featured: false,
    },
    {
      id: "bank-swing",
      title: "Bank Management System (Swing + OOP)",
      cat: "swing",
      badge: "Java Swing",
      desc: "Full GUI banking application combining Swing with OOP design. Supports account creation, deposits, withdrawals, and transaction history.",
      tech: ["Java", "Swing", "OOP"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Bank-Management-System-using-Java-Swing-and-OOP-Concepts",
      featured: false,
    },
    {
      id: "movie-gui",
      title: "Movie Ticket Booking System (GUI)",
      cat: "swing",
      badge: "Java Swing",
      desc: "Swing GUI for movie ticket booking with a visual seat map, showtime selection, and printable billing — a polished GUI version of the console project.",
      tech: ["Java", "Swing", "GUI"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Movie-Ticket-Booking-System-Using-Java",
      featured: false,
    },
    {
      id: "dice-game",
      title: "Dice Game (Player vs Computer)",
      cat: "python",
      badge: "Python",
      desc: "Interactive terminal dice game where a player competes against the computer with score tracking and re-play options.",
      tech: ["Python", "Random", "Game Logic"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Dice-Game-Player-vs-Computer-using-Python",
      featured: false,
    },
    {
      id: "password-checker",
      title: "Password Checker",
      cat: "python",
      badge: "Python",
      desc: "Validates password strength based on length, character types, and common patterns — provides feedback and a strength score to the user.",
      tech: ["Python", "Regex", "Security"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Valid-Password-Checker-Using-Python",
      featured: false,
    },
    {
      id: "student-csv",
      title: "Student Record System (CSV-based)",
      cat: "python",
      badge: "Python",
      desc: "CSV-backed student record manager for adding, viewing, searching, and deleting student data — persistent storage without a database.",
      tech: ["Python", "CSV", "File I/O"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Student-Record-Management-System-using-CSV-in-Python",
      featured: false,
    },
    {
      id: "student-python-csv",
      title: "Student Management System (CSV-based)",
      cat: "python",
      badge: "Python",
      desc: "Python student management app with CSV persistence — create, view, update, and delete records through a menu-driven interface.",
      tech: ["Python", "CSV", "File I/O"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Student-Management-System-Using-Python-CSV-based-",
      featured: false,
    },
    {
      id: "notes-saver",
      title: "Notes Saver System",
      cat: "python",
      badge: "Python",
      desc: "Terminal app to create, view, and delete personal notes saved to local text files — a minimal personal knowledge manager.",
      tech: ["Python", "File I/O", "CLI"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Notes-Saver-System-Using-Python-",
      featured: false,
    },
    {
      id: "library-python",
      title: "Library System (Python)",
      cat: "python",
      badge: "Python",
      desc: "Python-based library management for books — issue, return, search, and display available titles using structured data handling.",
      tech: ["Python", "OOP", "Lists"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Library-Management-System-Using-Python",
      featured: false,
    },
    {
      id: "rps-game",
      title: "Rock Paper Scissors Game",
      cat: "python",
      badge: "Python",
      desc: "Classic Rock Paper Scissors against a computer opponent with score tracking, replay, and best-of-N mode.",
      tech: ["Python", "Random", "Game Logic"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Rock-Paper-Scissors-Game-Using-Python",
      featured: false,
    },
    {
      id: "mcq-quiz",
      title: "MCQ Quiz App",
      cat: "python",
      badge: "Python",
      desc: "Terminal multiple-choice quiz application with configurable question sets, timer per question, and a final score display.",
      tech: ["Python", "JSON", "Logic"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/MCQ_quiz_app_using_python",
      featured: false,
    },
    {
      id: "number-guessing",
      title: "Number Guessing Game",
      cat: "python",
      badge: "Python",
      desc: "Guess-the-number game with difficulty levels, limited attempts, and hints (higher/lower) — a clean intro to Python game logic.",
      tech: ["Python", "Random", "Game Logic"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/Number-Guessing-Game-Using-Python-",
      featured: false,
    },
    {
      id: "atm-system",
      title: "ATM System",
      cat: "python",
      badge: "Python",
      desc: "Simulates a full ATM workflow — PIN authentication, deposit, withdrawal, balance check, and mini-statement in a terminal environment.",
      tech: ["Python", "OOP", "Authentication"],
      live: "",
      repo: "https://github.com/Karthikeyan-k-u/ATM_System_using_Python-",
      featured: false,
    },
  ],
};
